import Link from "next/link";
import { notFound } from "next/navigation";
import { and, eq } from "drizzle-orm";
import { decisionApprovals, getDb, productEvents } from "@railor/database";
import { loadDecision, loadDecisionEvents, decisionAuthorization } from "@railor/core";
import { requireSession } from "../../../../lib/auth";
import { ApprovalReview, ControlButton } from "../../../../components/app/control-forms";
import { ProductBadge } from "../../../../components/app/product-ui";

export const dynamic = "force-dynamic";
export const metadata = { title: "Decision" };

const RESULT_TONE: Record<string, string> = { pass: "good", fail: "bad", unknown: "warn", not_applicable: "neutral" };

/** Every rule's verdict in plain language; the raw payload stays one click away for audits. */
function RuleTable({ evaluation }: { evaluation: Record<string, unknown> }) {
  const rules = Array.isArray(evaluation.ruleResults) ? (evaluation.ruleResults as Array<{ rule: string; result: string; message: string }>) : [];
  return <details className="mt-4 group" open={rules.some((r) => r.result === "fail")}>
    <summary className="cursor-pointer text-sm font-semibold">Rule evaluation · {rules.filter((r) => r.result === "pass").length} pass · {rules.filter((r) => r.result === "fail").length} fail · {rules.filter((r) => r.result === "unknown").length} unknown</summary>
    {rules.length ? <ul className="mt-3 divide-y divide-[var(--color-line)] overflow-hidden rounded-xl border border-[var(--color-line)]">{rules.map((r, i) => <li key={`${r.rule}-${i}`} className="grid gap-2 bg-[var(--color-paper)] px-4 py-3 text-sm sm:grid-cols-[140px_minmax(0,220px)_1fr] sm:items-center"><span className="product-badge" data-tone={RESULT_TONE[r.result] ?? "neutral"}>{r.result.replaceAll("_", " ")}</span><span className="product-mono break-all text-[var(--color-ink-soft)]">{r.rule}</span><span className="text-[13px] leading-relaxed text-[var(--color-muted)]">{r.message}</span></li>)}</ul> : null}
    <details className="mt-3"><summary className="cursor-pointer text-xs text-[var(--color-muted)]">Raw evaluation</summary><pre className="mt-2 max-h-96 overflow-auto rounded-lg bg-[var(--color-paper)] p-4 text-xs">{JSON.stringify(evaluation, null, 2)}</pre></details>
  </details>;
}
export default async function DecisionPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const session = await requireSession(); if (!session.organization) return null;
  const org = session.organization.id; const loaded = await loadDecision(org, id); if (!loaded) notFound();
  const { decision, candidates } = loaded; const db = await getDb();
  const [events, reviews, approvals, authorization] = await Promise.all([
    loadDecisionEvents(org, id), db.select().from(productEvents).where(and(eq(productEvents.organizationId, org), eq(productEvents.targetId, id))).orderBy(productEvents.createdAt),
    db.select().from(decisionApprovals).where(and(eq(decisionApprovals.organizationId, org), eq(decisionApprovals.decisionId, id))), decisionAuthorization(org, id),
  ]);
  const approval = approvals[0];
  const explanation = decision.explain as { whySelected?: string[]; missingInformation?: string[]; whatWouldChange?: string[] };
  return <div className="product-page space-y-7"><Link href="/app/decisions" className="product-quiet-link">← Decision history</Link>
    <section className="product-dark p-6 sm:p-9"><span className="product-eyebrow">Initial evaluation / {decision.mode.toUpperCase()}</span><div className="relative z-10 grid gap-7 lg:grid-cols-[minmax(0,1fr)_minmax(260px,.45fr)]"><div><h1 className="font-display text-4xl font-semibold leading-none tracking-[-.05em] sm:text-6xl">{decision.status.replaceAll("_", " ").toUpperCase()}</h1><p className="mt-5 font-display text-xl text-[#f5e7d9]">{String(decision.intentSnapshot.sourceCurrency ?? decision.intentSnapshot.sourceAsset ?? "Source")} <span className="px-2 text-[#ff9a70]">→</span> {String(decision.intentSnapshot.destinationCurrency ?? decision.intentSnapshot.destinationCountry ?? "Destination")}</p><p className="mt-2 text-sm text-[#c8c0b6]">{decision.proposedExecutor ?? decision.recommendedProviderSlug ?? "No eligible provider"}</p></div><div className="border-t border-white/20 pt-4 lg:border-l lg:border-t-0 lg:pl-6 lg:pt-0"><p className="product-mono text-[#b5aaa0]">CURRENT AUTHORIZATION</p><p className="mt-2 font-display text-xl">{authorization.reason.replaceAll("_", " ")}</p><p className="mt-2 text-xs leading-relaxed text-[#b5aaa0]">The initial result stays in the record; approval or revalidation changes current authorization.</p><div className="mt-5 flex flex-wrap gap-3">{session.role !== "viewer" && <ControlButton command={{ action: "revalidate", id }}>Revalidate</ControlButton>}<Link href={`/app/policies/${decision.policyId}`} className="self-center text-xs text-[#ffad8c] underline underline-offset-4">Policy v{decision.policyVersionNumber} ↗</Link></div></div></div><div className="relative z-10 mt-7 border-t border-white/15 pt-4 text-xs text-[#b5aaa0]"><span className="product-mono break-all">Decision hash {decision.decisionHash}</span>{decision.previousDecisionId && <Link className="ml-3 text-[#ffad8c] underline" href={`/app/decisions/${decision.previousDecisionId}`}>Previous decision ↗</Link>}</div></section>
    <section className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_minmax(280px,.55fr)]"><div className="product-panel p-5 sm:p-7"><span className="product-eyebrow">Reasoning / 01</span><h2 className="font-display text-2xl font-semibold">Why this decision</h2><div className="mt-5 space-y-3">{[...(explanation.whySelected ?? []), ...decision.warnings, ...(explanation.missingInformation ?? []), ...(explanation.whatWouldChange ?? [])].map((line, index) => <p className="flex gap-3 border-b border-[var(--color-line)] pb-3 text-sm leading-relaxed last:border-0" key={index}><span className="product-index">{String(index + 1).padStart(2, "0")}</span>{line}</p>)}</div></div>
      <div className="product-panel p-5 sm:p-7"><span className="product-eyebrow">Input / 02</span><h2 className="font-display text-2xl font-semibold">Payment intent</h2><dl className="mt-5 grid grid-cols-2 gap-4 text-sm"><div><dt className="product-index">AMOUNT</dt><dd className="mt-1 font-display text-2xl font-semibold tabular">{String(decision.intentSnapshot.amount)}</dd></div><div><dt className="product-index">MODE</dt><dd className="mt-1 capitalize">{decision.mode}</dd></div></dl><details className="mt-5 border-t border-[var(--color-line)] pt-4"><summary className="cursor-pointer text-sm font-semibold">View full intent data</summary><pre className="mt-3 max-h-72 overflow-auto rounded-lg bg-[var(--color-paper)] p-3 text-xs">{JSON.stringify(decision.intentSnapshot, null, 2)}</pre></details></div></section>
    {approval && <section className="product-panel p-5 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-display text-xl font-semibold">Approval · {approval.expiresAt.getTime() <= Date.now() && ["approved", "pending"].includes(approval.status) ? "expired" : approval.status}</h2><ProductBadge status={approval.status} /></div><p className="mt-2 text-sm text-[var(--color-muted)]">Expires {approval.expiresAt.toISOString()}. A different owner or admin must approve a payment you submitted.</p>{["owner", "admin"].includes(session.role ?? "") && <div className="mt-5 border-t border-[var(--color-line)] pt-5"><ApprovalReview id={approval.id} status={approval.status} /></div>}</section>}
    <section className="space-y-3"><span className="product-eyebrow">Options / 03</span><h2 className="font-display text-2xl font-semibold">Provider evaluations</h2>{candidates.map((candidate) => <article className="product-panel p-5 sm:p-6" key={candidate.id}><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-display text-lg font-semibold">{candidate.providerName}</h3><ProductBadge status={candidate.policyResult} /></div><p className="product-mono mt-3 text-[var(--color-muted)]">Route {candidate.routeCertainty ?? "unknown"} · Entity {candidate.entityEligibility ?? "unknown"}{candidate.selected ? " · Selected" : ""}</p><RuleTable evaluation={candidate.policyEvaluation} />{candidate.evidenceIds.length > 0 && <p className="mt-3 break-all text-xs text-[var(--color-muted)]">Evidence references: {candidate.evidenceIds.join(", ")}</p>}</article>)}</section>
    <section className="space-y-3"><span className="product-eyebrow">Record / 04</span><h2 className="font-display text-2xl font-semibold">Audit events</h2><div className="product-panel divide-y divide-[var(--color-line)]">{events?.map((event) => <p className="grid gap-2 p-4 text-sm sm:grid-cols-[190px_1fr]" key={event.id}><time className="product-mono text-[var(--color-muted)]">{event.createdAt.toISOString()}</time>{event.detail}</p>)}{reviews.map((event) => <p className="grid gap-2 p-4 text-sm sm:grid-cols-[190px_1fr]" key={event.id}><time className="product-mono text-[var(--color-muted)]">{event.createdAt.toISOString()}</time>{event.kind} · {String(event.data.comment ?? "")}</p>)}</div></section>
  </div>;
}
